#ifndef __A_ACTION_HPP__
#define __A_ACTION_HPP__

#include "h2def.hpp" // MAXPLAYERS

extern int localQuakeHappening[MAXPLAYERS];

void A_BatMove(mobj_t * actor);
void A_BatSpawnInit(mobj_t * actor);
void A_BatSpawn(mobj_t * actor);
void A_BellReset1(mobj_t * actor);
void A_BellReset2(mobj_t * actor);
void A_BishopAttack();
void A_BishopAttack2();
void A_BishopChase();
void A_BishopDecide();
void A_BishopDoBlur();
void A_BishopMissileSeek();
void A_BishopMissileWeave();
void A_BishopPainBlur();
void A_BishopPuff();
void A_BishopSpawnBlur();
void A_BounceCheck();
void A_BridgeInit(mobj_t * actor);
void A_BridgeOrbit(mobj_t * actor);
void A_CentaurAttack();
void A_CentaurAttack2();
void A_CentaurDefend();
void A_CentaurDropStuff();
void A_CFlameAttack();
void A_CFlameMissile();
void A_CFlamePuff();
void A_CFlameRotate();
void A_Chase();
void A_CheckBurnGone();
void A_CheckFloor();
void A_CheckSkullDone();
void A_CheckSkullFloor();
void A_CheckTeleRing(mobj_t * actor);
void A_CheckThrowBomb(mobj_t * actor);
void A_CHolyAttack();
void A_CHolyAttack2();
void A_CHolyCheckScream();
void A_CHolyPalette();
void A_CHolySeek();
void A_CHolySpawnPuff();
void A_CHolyTail();
void A_ClassBossHealth();
void A_ClericAttack();
void A_CMaceAttack();
void A_ContMobjSound(mobj_t * actor);
void A_CorpseBloodDrip(mobj_t * actor);
void A_CorpseExplode(mobj_t * actor);
void A_CStaffAttack();
void A_CStaffCheck();
void A_CStaffCheckBlink();
void A_CStaffInitBlink();
void A_CStaffMissileSlither();
void A_DelayGib();
void A_Demon2Death();
void A_DemonAttack1();
void A_DemonAttack2();
void A_DemonDeath();
void A_DragonAttack();
void A_DragonCheckCrash();
void A_DragonFlap();
void A_DragonFlight();
void A_DragonFX2();
void A_DragonInitFlight();
void A_DragonPain();
void A_DropMace();
void A_ESound(mobj_t * actor);
void A_EttinAttack();
void A_Explode();
void A_FaceTarget();
void A_FastChase();
void A_FAxeAttack();
void A_FHammerAttack();
void A_FHammerThrow();
void A_FighterAttack();
void A_FireConePL1();
void A_FiredAttack();
void A_FiredChase();
void A_FiredRocks();
void A_FiredSplotch();
void A_FlameCheck(mobj_t * actor);
void A_FloatGib();
void A_FogMove(mobj_t * actor);
void A_FogSpawn(mobj_t * actor);
void A_FPunchAttack();
void A_FreeTargMobj();
void A_FreezeDeath();
void A_FreezeDeathChunks();
void A_FSwordAttack();
void A_FSwordFlames();
void A_HideThing(mobj_t * actor);
void A_IceCheckHeadDone();
void A_IceGuyAttack();
void A_IceGuyChase();
void A_IceGuyDie();
void A_IceGuyLook();
void A_IceGuyMissileExplode();
void A_IceGuyMissilePuff();
void A_IceSetTics();
void A_KBolt();
void A_KBoltRaise();
void A_KoraxBonePop();
void A_KoraxChase();
void A_KoraxCommand();
void A_KoraxDecide();
void A_KoraxMissile();
void A_KoraxStep();
void A_KoraxStep2();
void A_KSpiritRoam();
void A_LastZap();
void A_LeafCheck(mobj_t * actor);
void A_LeafSpawn(mobj_t * actor);
void A_LeafThrust(mobj_t * actor);
void A_Light0();
void A_LightningClip();
void A_LightningReady();
void A_LightningRemove();
void A_LightningZap();
void A_Look();
void A_Lower();
void A_MageAttack();
void A_MinotaurAtk1();
void A_MinotaurAtk2();
void A_MinotaurAtk3();
void A_MinotaurCharge();
void A_MinotaurChase();
void A_MinotaurDecide();
void A_MinotaurFade0();
void A_MinotaurFade1();
void A_MinotaurFade2();
void A_MinotaurLook();
void A_MinotaurRoam();
void A_MLightningAttack();
void A_MntrFloorFire();
void A_MStaffAttack();
void A_MStaffPalette();
void A_MStaffTrack();
void A_MStaffWeave();
void A_MWandAttack();
void A_NoBlocking();
void A_NoGravity(mobj_t * actor);
void A_Pain();
void A_PigAttack();
void A_PigChase();
void A_PigLook();
void A_PigPain();
void A_PoisonBagCheck(mobj_t * actor);
void A_PoisonBagDamage(mobj_t * actor);
void A_PoisonBagInit(mobj_t * actor);
void A_PoisonShroom(mobj_t * actor);
void A_PotteryCheck(mobj_t * actor);
void A_PotteryChooseBit(mobj_t * actor);
void A_PotteryExplode(mobj_t * actor);
void A_Quake(mobj_t * actor);
void A_QueueCorpse();
void A_Raise();
void A_ReFire();
void A_RestoreArtifact();
void A_RestoreSpecialThing1();
void A_RestoreSpecialThing2();
void A_Scream();
void A_SerpentBirthScream();
void A_SerpentChase();
void A_SerpentCheckForAttack();
void A_SerpentChooseAttack();
void A_SerpentDiveSound();
void A_SerpentHeadCheck();
void A_SerpentHeadPop();
void A_SerpentHide();
void A_SerpentHumpDecide();
void A_SerpentLowerHump();
void A_SerpentMeleeAttack();
void A_SerpentMissileAttack();
void A_SerpentRaiseHump();
void A_SerpentSpawnGibs();
void A_SerpentUnHide();
void A_SerpentWalk();
void A_SetAltShadow(mobj_t * actor);
void A_SetReflective();
void A_SetShootable(mobj_t * actor);
void A_ShedShard();
void A_SinkGib();
void A_SkullPop();
void A_SmBounce();
void A_SmokePuffExit();
void A_SnoutAttack();
void A_SoAExplode(mobj_t * actor);
void A_SorcBallOrbit();
void A_SorcBallPop();
void A_SorcBossAttack();
void A_SorcererBishopEntry();
void A_SorcFX1Seek();
void A_SorcFX2Orbit();
void A_SorcFX2Split();
void A_SorcFX4Check();
void A_SorcSpinBalls();
void A_SpawnBishop();
void A_SpawnFizzle();
void A_SpeedBalls();
void A_SpeedFade();
void A_Summon(mobj_t * actor);
void A_TeloSpawnA(mobj_t * actor);
void A_TeloSpawnB(mobj_t * actor);
void A_TeloSpawnC(mobj_t * actor);
void A_TeloSpawnD(mobj_t * actor);
void A_ThrustBlock(mobj_t * actor);
void A_ThrustImpale(mobj_t * actor);
void A_ThrustInitDn(mobj_t * actor);
void A_ThrustInitUp(mobj_t * actor);
void A_ThrustLower(mobj_t * actor);
void A_ThrustRaise(mobj_t * actor);
void A_TreeDeath(mobj_t * actor);
void A_UnHideThing(mobj_t * actor);
void A_UnSetInvulnerable();
void A_UnSetReflective();
void A_UnSetShootable(mobj_t * actor);
void A_WeaponReady();
void A_WraithChase();
void A_WraithFX2();
void A_WraithFX3();
void A_WraithInit();
void A_WraithLook();
void A_WraithMelee();
void A_WraithMissile();
void A_WraithRaise();
void A_WraithRaiseInit();
void A_ZapMimic();


#endif //__A_ACTION_HPP__