add_library(doom STATIC)

target_sources(doom 
    PRIVATE 
        am_map.cpp
        deh_ammo.cpp
        deh_bexincl.cpp
        deh_bexpars.cpp   
        deh_bexptr.cpp
        deh_bexstr.cpp
        deh_cheat.cpp
        deh_doom.cpp
        deh_frame.cpp
        deh_misc.cpp
        deh_ptr.cpp
        deh_sound.cpp
        deh_thing.cpp
        deh_weapon.cpp
        d_items.cpp       
        d_main.cpp
        d_net.cpp
        doomdef.cpp       
        doomstat.cpp      
        dstrings.cpp      
        f_finale.cpp      
        f_wipe.cpp        
        g_game.cpp        
        hu_lib.cpp        
        hu_stuff.cpp      
        info.cpp
        m_crispy.cpp      
        m_menu.cpp        
        m_random.cpp      
        p_bexptr.cpp
        p_blockmap.cpp
        p_ceilng.cpp
        p_doors.cpp
        p_enemy.cpp
        p_extnodes.cpp
        p_extsaveg.cpp
        p_floor.cpp
        p_inter.cpp       
        p_lights.cpp
        p_map.cpp
        p_maputl.cpp
        p_mobj.cpp        
        p_plats.cpp
        p_pspr.cpp
        p_saveg.cpp
        p_setup.cpp
        p_sight.cpp
        p_spec.cpp
        p_switch.cpp
        p_telept.cpp
        p_tick.cpp
        p_user.cpp
        r_bmaps.cpp
        r_bsp.cpp
        r_data.cpp
        r_draw.cpp
        r_main.cpp
        r_plane.cpp
        r_segs.cpp
        r_sky.cpp
        r_swirl.cpp
        r_things.cpp
        s_musinfo.cpp
        s_sound.cpp
        sounds.cpp
        statdump.cpp
        st_lib.cpp
        st_stuff.cpp
        wi_stuff.cpp
        tables.cpp
        
    PRIVATE FILE_SET HEADERS FILES
        am_map.hpp
        deh_bexpars.hpp
        deh_misc.hpp
        d_englsh.hpp
        d_items.hpp
        d_main.hpp
        d_net.hpp
        doomdata.hpp
        doomdef.hpp
        doomstat.hpp
        d_player.hpp
        dstrings.hpp
        d_textur.hpp
        d_think.hpp
        f_finale.hpp
        f_wipe.hpp
        g_game.hpp
        hu_lib.hpp
        hu_stuff.hpp
        info.hpp
        m_background.hpp
        m_crispy.hpp
        m_menu.hpp
        m_random.hpp
        p_extnodes.hpp
        p_extsaveg.hpp
        p_inter.hpp
        p_local.hpp
        p_mobj.hpp
        p_pspr.hpp
        p_saveg.hpp
        p_setup.hpp
        p_spec.hpp
        p_tick.hpp
        r_bmaps.hpp
        r_bsp.hpp
        r_data.hpp
        r_defs.hpp
        r_draw.hpp
        r_local.hpp
        r_main.hpp
        r_plane.hpp
        r_segs.hpp
        r_sky.hpp
        r_state.hpp
        r_swirl.hpp
        r_things.hpp
        s_musinfo.hpp
        s_sound.hpp
        sounds.hpp
        statdump.hpp
        st_lib.hpp
        st_stuff.hpp
        tables.hpp
        wi_stuff.hpp 
        event_function_decls.hpp

    PUBLIC FILE_SET CXX_MODULES FILES
        #m_fixed.cxx
)

target_include_directories(doom PRIVATE "../" "${CMAKE_CURRENT_BINARY_DIR}/../../")
target_link_libraries(doom cpp_modules SDL2::SDL2 SDL2::mixer SDL2::net)
